### PR TITLE
make the script even MORE stealthy

### PR DESCRIPTION
**Pull request by lfuelling**
Modern browsers have base64 support included.

### CODE REVIEW

**Review by mischah — APPROVED** [review]
Hah, this is the most stealthiest Rickrolling experience ever.

**Comment by mischah** [comment]
Thanks @lfuelling 👌

**Comment by Haroenv** [comment]
I wonder if we could make an iframe on the page and replace it instead of letting you press the back button, which can also be disabled :trollface:

**Comment by lfuelling** [comment]
Or something like a4972e7d5265d6b35431ea6f6d5bd7cce6eb377b?

**Comment by Haroenv** [comment]
nice idea!

**Comment by lfuelling** [comment]
But doesn't work on safari :c

**Comment by 0x04** [comment]
Yeah and I'm sorry for not having safari as a testable device. I have my iPod (iOS < 11) nothing else.

**Pull request merged**
